services:
  hummingbot:
    container_name: hummingbot
    image: mlguys/hummingbot-hydration
    volumes:
      - ./volumes/client/conf:/home/hummingbot/conf
      - ./volumes/client/conf/connectors:/home/hummingbot/conf/connectors
      - ./volumes/client/conf/strategies:/home/hummingbot/conf/strategies
      - ./volumes/client/conf/controllers:/home/hummingbot/conf/controllers
      - ./volumes/client/conf/scripts:/home/hummingbot/conf/scripts
      - ./volumes/client/logs:/home/hummingbot/logs
      - ./volumes/client/data:/home/hummingbot/data
      - ./volumes/client/scripts:/home/hummingbot/scripts
      - ./volumes/client/controllers:/home/hummingbot/controllers
      - ./volumes/common/certs:/home/hummingbot/certs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    env_file:
      - .env
    tty: true
    stdin_open: true
    network_mode: "host"
  gateway:
    container_name: gateway
    image: mlguys/gateway-hydration
    ports:
      - "15888:15888"
      - "8080:8080"
    volumes:
      - ./volumes/gateway/conf:/home/gateway/conf
      - ./volumes/gateway/logs:/home/gateway/logs
      - ./volumes/common/certs:/home/gateway/certs
    environment:
      - GATEWAY_PASSPHRASE=${GATEWAY_PASSPHRASE}
    tty: true
    stdin_open: true
